name: CI/CD - Workflow

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      - name: ES Lint
      - run: |
          npm run lint
      - name: Run Tests
      - run: |
          npm run test
    
