  name: CI/CD - Workflow

  on:
    push:
      branches: [master]

  jobs:
    backend:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Node.js (Backend)
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Backend Dependencies
          run: |
            cd backend
            npm install
        - name: Run ESLint (Backend)
          run: |
            cd backend
            npm install --save-dev eslint @eslint/js
            npm run lint --fix
        - name: Run Tests (Backend)
          run: |
            cd backend
            npm run build
            npm run test

    # frontend:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v3
    #     - name: Setup Node.js (Frontend)
    #       uses: actions/setup-node@v3
    #       with:
    #         node-version: 18
    #     - name: Install Frontend Dependencies
    #       run: |
    #         cd frontend
    #         npm install
    #     - name: Run ESLint (Frontend)
    #       run: |
    #         cd frontend
    #         npm install --save-dev eslint
    #         npm run lint
    #     - name: Run Tests (Frontend)
    #       run: |
    #         cd frontend
    #         npm run test
